name: scapy
base: core18
version: 'git'
summary: Interactive packet manipulation program
description: >
  Scapy is able to forge or decode packets of a wide number of protocols,
  send them on the wire, capture them, store or read them using pcap files,
  match requests and replies, and much more. It is designed to allow fast
  packet prototyping by using default values that work.

grade: stable
confinement: strict

parts:
  scapy:
    plugin: python
    source: .
    python-packages:
      - cryptography
      - matplotlib
      - PyX
    stage-packages:
      - fontconfig-config
      - graphviz
      - imagemagick
      - ipython3
      - tcpdump
      - texlive

apps:
  scapy:
    command: bin/scapy
    plugs:
      - home
      - network
      - network-observe